const poemText = [
  "Looking at your smile. ",
  "Laying next to you. ",
  "Making you laugh. ",
  "Staring into your eyes. ",
  "Walking with you and holding hands. ",
  "Listening to what you say. ",
  "Giving you hugs. ",
  "Thinking about you. ",
  "Caressing your hair. ",
  "Holding you in my arms. ",
  "The sound of your voice. ",
  "Touching you. ",
  "Your cute cheeks. ",
  "The smell of your hair. ",
  "Our adventures. ",
  "Our gambling addictions. ",
  "The chuckles and giggles. ",
  "Your great sense of fashion. ",
  "The pinches you give to my hand. ",
  "The lips on your face. ",
  "The thought of you. ",
  "How right you are 99.99% of the time. ",
  "The kisses you give. ",
  "When you visit my dreams. ",
  "Your big kisses. ",
  "Your tiny kisses. ",
  "Your dynamic nails. ",
  "Receiving your text messages. ",
  "The birthmarks on your face. ",
  "The little accessories you wear. ",
  "For being my muse. ",
  "Your point of view. ",
  "Your competitiveness. ",
  "The shadows of your face. ",
  "A kissable neck. ",
  "Your soft hands. ",
  "Pictures of you. ",
  "Your dope taste in music. ",
  "The little glimmer in your eye. ",
  "Your values on family. ",
  "Our awkward silences and the smile that comes after. ",
  "Talking to you about everything and nothing. ",
  "You being first at stuff (it challenges me to learn more about you to be first next time)",
  "The scent on the sweater you left behind. ",
  "Learning about you. ",
  "Hearing about your day. ",
  "Your company. ",
  "Your opinions. ",
  "Your personality. ",
  "How sweet you are. ",
  "The butterflies you give my stomach. ",
  "The new things you lead me to discover. ",
  "Your face when you get excited. ",
  "The way you decorate your hands. ",
  "Your peace. ",
  "Your warmth. ",
  "Your silhouette. ",
  "What you inspire me to be. ",
  "The way you drive me crazy. ",
  "When you scratch the palm of my hand. ",
  "When you ask me to scratch your back. ",
  "The scent that you leave behind. ",
  "Touching your face to feel all the beautiful details in it. ",
  "The lines in your hand I trace as I try to remember them. ",
  "Your drawings on noteit. ",
  "How freakin adorable you are. ",
  "Your name when it rings in my head. ",
  "Your hellos. ",
  "The pictures of you. ",
  "Our walks and you holding my arm. ",
  "Your pictures on my phone. ",
  "Your text when they give me aha! Moments. ",
  "When you ask me what I'm looking at you when I'm admiring you. ",
  "Talking about the future with you. ",
  "When we are acting goofy. ",
  "Your smile again cause it's that great and some things are worth repeating. ",
  "How your face glimmers when the sun hits your face. ",
  "All the birthmarks that make your face so beautiful. ",
  "Your arms and their comfort. ",
  "Your soothing humming. ",
  "The taste of your lips. ",
  "Your voice over the phone. ",
  "The way you remind me of happy moments and how I desire to have more happy moments with you. ",
  "When you say “hello” to get my attention. ",
  "Your support on my silliness. ",
  "When you make everything seem so much better when I'm feeling cranky. ",
  "When you wake me up at night to tell me I'm snoring (I get to see your cute face)",
  "The different forms of your smile, big smile, small smile, laugh smiles, eye squinting smiles, all your smiles. ",
  "(I don't love missing you) Just being by your side. ",
  "How much I care about you and how much you care about me. ",
  "When you lean closer when I am gonna kiss you in your cheek. ",
  "Your waist I get to hold when you don't have a big coat. ",
  "Your voice in Spanish. ",
  "Your butt (cause why shouldn't I include it here if it's part of the list). ",
  "When I tell you you are the cutest and you say noo with the cutest smile in the world. ",
  "When you listen to me rant about things. ",
  "When you wake me up so I can hug you. ",
  "Being able to share first experiences with you. ",
  "Falling in love with you over and over again. ",
  "Getting lost in your beautiful stare, smile, and face. ",
  "Discovering your taste, likes, and dislikes. ",
  "The things we get to check of our list. ",
  "Tu voz en español. ",
  "Our experimentation. ",
  "Remembering those times looking at our list. ",
  "The beauty that is you. ",
  "Taking pictures of you (cause you are my muse)",
  ]

export default poemText;